pub mod city;

use city::*;
use strum::{Display, EnumString};

// in future if phf support enum as key enum must be replace with string
pub static PROVINCES: phf::Map<&str, Province> = phf::phf_map! {
    "Alborz" => Province{
        prefix_phone : 26,
        farsi_name : "",
        latin_name : "",
        cities : &ALBORZ_CITIES,
    },
    "Ardabil" => Province{
        prefix_phone : 45,
        farsi_name : "",
        latin_name : "",
        cities : &ARDABIL_CITIES,
    },
    "AzerbaijanEast" => Province{
        prefix_phone : 41,
        farsi_name : "",
        latin_name : "",
        cities : &AZERBAIJAN_EAST_CITIES,
    },
    "AzerbaijanWest" => Province{
        prefix_phone : 44,
        farsi_name : "",
        latin_name : "",
        cities : &AZERBAIJAN_WEST_CITIES,
    },
    "Bushehr" => Province{
        prefix_phone : 77,
        farsi_name : "",
        latin_name : "",
        cities : &BUSHEHR_CITIES,
    },
    "ChaharMahaalAndBakhtiari" => Province{
        prefix_phone : 38,
        farsi_name : "",
        latin_name : "",
        cities : &CHAHARMAHAAL_AND_BAKHTIARI_CITIES,
    },
    "Fars" => Province{
        prefix_phone : 71,
        farsi_name : "",
        latin_name : "",
        cities : &FARS_CITIES,
    },
    "Gilan" => Province{
        prefix_phone : 13,
        farsi_name : "",
        latin_name : "",
        cities : &GILAN_CITIES,
    },
    "Golestan" => Province{
        prefix_phone : 17,
        farsi_name : "",
        latin_name : "",
        cities : &GOLESTAN_CITIES,
    },
    "Hamadan" => Province{
        prefix_phone : 81,
        farsi_name : "",
        latin_name : "",
        cities : &HAMADAN_CITIES,
    },
    "Hormozgan" => Province{
        prefix_phone : 76,
        farsi_name : "",
        latin_name : "",
        cities : &HORMOZGAN_CITIES,
    },
    "Ilam" => Province{
        prefix_phone : 84,
        farsi_name : "",
        latin_name : "",
        cities : &ILAM_CITIES,
    },
    "Isfahan" => Province{
        prefix_phone : 31,
        farsi_name : "",
        latin_name : "",
        cities : &ISFAHAN_CITIES,
    },
    "Kerman" => Province{
        prefix_phone : 34,
        farsi_name : "",
        latin_name : "",
        cities : &KERMAN_CITIES,
    },
    "Kermanshah" => Province{
        prefix_phone : 83,
        farsi_name : "",
        latin_name : "",
        cities : &KERMANSHAH_CITIES,
    },
    "KhorasanNorth" => Province{
        prefix_phone : 58,
        farsi_name : "",
        latin_name : "",
        cities : &KHORASAN_NORTH_CITIES,
    },
    "KhorasanRazavi" => Province{
        prefix_phone : 51,
        farsi_name : "",
        latin_name : "",
        cities : &KHORASAN_RAZAVI_CITIES,
    },
    "KhorasanSouth" => Province{
        prefix_phone : 56,
        farsi_name : "",
        latin_name : "",
        cities : &KHORASAN_SOUTH_CITIES,
    },
    "Khuzestan" => Province{
        prefix_phone : 61,
        farsi_name : "",
        latin_name : "",
        cities : &KHUZESTAN_CITIES,
    },
    "KohgiluyehAndBoyerAhmad" => Province{
        prefix_phone : 74,
        farsi_name : "",
        latin_name : "",
        cities : &KOHGILUYEH_ANDBOYER_AHMAD_CITIES,
    },
    "Kurdistan" => Province{
        prefix_phone : 78,
        farsi_name : "",
        latin_name : "",
        cities : &KURDISTAN_CITIES,
    },
    "Lorestan" => Province{
        prefix_phone : 66,
        farsi_name : "",
        latin_name : "",
        cities : &LORESTAN_CITIES,
    },
    "Markazi" => Province{
        prefix_phone : 86,
        farsi_name : "",
        latin_name : "",
        cities : &MARKAZI_CITIES,
    },
    "Mazandaran" => Province{
        prefix_phone : 11,
        farsi_name : "",
        latin_name : "",
        cities : &MAZANDARAN_CITIES,
    },
    "Qazvin" => Province{
        prefix_phone : 28,
        farsi_name : "",
        latin_name : "",
        cities : &QAZVIN_CITIES,
    },
    "Qom" => Province{
        prefix_phone : 25,
        farsi_name : "",
        latin_name : "",
        cities : &QOM_CITIES,
    },
    "Semnan" => Province{
        prefix_phone : 23,
        farsi_name : "",
        latin_name : "",
        cities : &SEMNAN_CITIES,
    },
    "SistanAndBaluchestan" => Province{
        prefix_phone : 54,
        farsi_name : "",
        latin_name : "",
        cities : &SISTAN_AND_BALUCHESTAN_CITIES,
    },
    "Tehran" => Province{
        prefix_phone : 21,
        farsi_name : "",
        latin_name : "",
        cities : &TEHRAN_CITIES,
    },
    "Yazd" => Province{
        prefix_phone : 35,
        farsi_name : "",
        latin_name : "",
        cities : &YAZD_CITIES,
    },
    "Zanjan" => Province{
        prefix_phone : 24,
        farsi_name : "",
        latin_name : "",
        cities : &ZANJAN_CITIES,
    },
};

#[derive(Debug, PartialEq, Eq, Hash, EnumString, Display)]
pub enum IranProvince {
    Alborz,
    Ardabil,
    AzerbaijanEast,
    AzerbaijanWest,
    Bushehr,
    ChaharMahaalAndBakhtiari,
    Fars,
    Gilan,
    Golestan,
    Hamadan,
    Hormozgan,
    Ilam,
    Isfahan,
    Kerman,
    Kermanshah,
    KhorasanNorth,
    KhorasanRazavi,
    KhorasanSouth,
    Khuzestan,
    KohgiluyehAndBoyerAhmad,
    Kurdistan,
    Lorestan,
    Markazi,
    Mazandaran,
    Qazvin,
    Qom,
    Semnan,
    SistanAndBaluchestan,
    Tehran,
    Yazd,
    Zanjan,
}

pub struct Province {
    pub prefix_phone: u32,
    pub farsi_name: &'static str,
    pub latin_name: &'static str,
    pub cities: &'static phf::Map<&'static str, city::City>,
}
