use crate::{create_fixed_map, utils::FixedMap};

#[derive(Debug)]
pub struct ShebaInfo {
    pub code: &'static str,
    pub nickname: &'static str,
    pub name: &'static str,
    pub persian_name: &'static str,
}

pub static SHEBA_CODE_TABLE: FixedMap<&str, ShebaInfo> = create_fixed_map! {
    "010" => ShebaInfo{
        nickname: "central-bank",
        name: "Central Bank of Iran",
        persian_name: "بانک مرکزی جمهوری اسلامی ایران",
        code: "010",
    },
    "011" => ShebaInfo{
        nickname: "sanat-o-madan",
        name: "Sanat O Madan Bank",
        persian_name: "بانک صنعت و معدن",
        code: "011",
    },
    "012" => ShebaInfo{
        nickname: "mellat",
        name: "Mellat Bank",
        persian_name: "بانک ملت",
        code: "012",
    },
    "013" => ShebaInfo{
        nickname: "refah",
        name: "Refah Bank",
        persian_name: "بانک رفاه کارگران",
        code: "013",
    },
    "014" => ShebaInfo{
        nickname: "maskan",
        name: "Maskan Bank",
        persian_name: "بانک مسکن",
        code: "014",
    },
    "015" => ShebaInfo{
        nickname: "sepah",
        name: "Sepah Bank",
        persian_name: "بانک سپه",
        code: "015",
    },
    "016" => ShebaInfo{
        nickname: "keshavarzi",
        name: "Keshavarzi",
        persian_name: "بانک کشاورزی",
        code: "016",
    },
    "017" => ShebaInfo{
        nickname: "melli",
        name: "Melli",
        persian_name: "بانک ملی ایران",
        code: "017",
    },
    "018" => ShebaInfo{
        nickname: "tejarat",
        name: "Tejarat Bank",
        persian_name: "بانک تجارت",
        code: "018",
    },
    "019" => ShebaInfo{
        nickname: "saderat",
        name: "Saderat Bank",
        persian_name: "بانک صادرات ایران",
        code: "019",
    },
    "020" => ShebaInfo{
        nickname: "tosee-saderat",
        name: "Tose Saderat Bank",
        persian_name: "بانک توسعه صادرات",
        code: "020",
    },
    "021" => ShebaInfo{
        nickname: "post",
        name: "Post Bank",
        persian_name: "پست بانک ایران",
        code: "021",
    },
    "022" => ShebaInfo{
        nickname: "toose-taavon",
        name: "Tosee Taavon Bank",
        persian_name: "بانک توسعه تعاون",
        code: "022",
    },
    "051" => ShebaInfo{
        nickname: "tosee",
        name: "Tosee Bank",
        persian_name: "موسسه اعتباری توسعه",
        code: "051",
    },
    "052" => ShebaInfo{
        nickname: "ghavamin",
        name: "Ghavamin Bank",
        persian_name: "بانک قوامین",
        code: "052",
    },
    "053" => ShebaInfo{
        nickname: "karafarin",
        name: "Karafarin Bank",
        persian_name: "بانک کارآفرین",
        code: "053",
    },
    "054" => ShebaInfo{
        nickname: "parsian",
        name: "Parsian Bank",
        persian_name: "بانک پارسیان",
        code: "054",
    },
    "055" => ShebaInfo{
        nickname: "eghtesad-novin",
        name: "Eghtesad Novin Bank",
        persian_name: "بانک اقتصاد نوین",
        code: "055",
    },
    "056" => ShebaInfo{
        nickname: "saman",
        name: "Saman Bank",
        persian_name: "بانک سامان",
        code: "056",
    },
    "057" => ShebaInfo{
        nickname: "pasargad",
        name: "Pasargad Bank",
        persian_name: "بانک پاسارگاد",
        code: "057",
    },
    "058" => ShebaInfo{
        nickname: "sarmayeh",
        name: "Sarmayeh Bank",
        persian_name: "بانک سرمایه",
        code: "058",
    },
    "059" => ShebaInfo{
        nickname: "sina",
        name: "Sina Bank",
        persian_name: "بانک سینا",
        code: "059",
    },
    "060" => ShebaInfo{
        nickname: "mehr-iran",
        name: "Mehr Iran Bank",
        persian_name: "بانک مهر ایران",
        code: "060",
    },
    "061" => ShebaInfo{
        nickname: "shahr",
        name: "City Bank",
        persian_name: "بانک شهر",
        code: "061",
    },
    "062" => ShebaInfo{
        nickname: "ayandeh",
        name: "Ayandeh Bank",
        persian_name: "بانک آینده",
        code: "062",
    },
    "063" => ShebaInfo{
        nickname: "ansar",
        name: "Ansar Bank",
        persian_name: "بانک انصار",
        code: "063",
    },
    "064" => ShebaInfo{
        nickname: "gardeshgari",
        name: "Gardeshgari Bank",
        persian_name: "بانک گردشگری",
        code: "064",
    },
    "065" => ShebaInfo{
        nickname: "hekmat-iranian",
        name: "Hekmat Iranian Bank",
        persian_name: "بانک حکمت ایرانیان",
        code: "065",
    },
    "066" => ShebaInfo{
        nickname: "dey",
        name: "Dey Bank",
        persian_name: "بانک دی",
        code: "066",
    },
    "069" => ShebaInfo{
        nickname: "iran-zamin",
        name: "Iran Zamin Bank",
        persian_name: "بانک ایران زمین",
        code: "069",
    },
    "070" => ShebaInfo{
        nickname: "resalat",
        name: "Resalat Bank",
        persian_name: "بانک قرض الحسنه رسالت",
        code: "070",
    },
    "073" => ShebaInfo{
        nickname: "kosar",
        name: "Kosar Credit Institute",
        persian_name: "موسسه اعتباری کوثر",
        code: "073",
    },
    "075" => ShebaInfo{
        nickname: "melal",
        name: "Melal Credit Institute",
        persian_name: "موسسه اعتباری ملل",
        code: "075",
    },
    "078" => ShebaInfo{
        nickname: "middle-east-bank",
        name: "Middle East Bank",
        persian_name: "بانک خاورمیانه",
        code: "078",
    },
    "080" => ShebaInfo{
        nickname: "noor-bank",
        name: "Noor Credit Institution",
        persian_name: "موسسه اعتباری نور",
        code: "080",
    },
    "079" => ShebaInfo{
        nickname: "mehr-eqtesad",
        name: "Mehr Eqtesad Bank",
        persian_name: "بانک مهر اقتصاد",
        code: "079",
    },
    "090" => ShebaInfo{
        nickname: "mehr-iran",
        name: "Mehr Iran Bank",
        persian_name: "بانک مهر ایران",
        code: "090",
    },
    "095" => ShebaInfo{
        nickname: "iran-venezuela",
        name: "Iran and Venezuela Bank",
        persian_name: "بانک ایران و ونزوئلا",
        code: "095",
    },
};
