name: Cargo Fmt

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check
      